In [2]:
# Pandas - similar to pqe in powerBi
# it is used for data inspecting, cleaning and tranformation
# very imp part in tour eda
# works on - Series and Dataframe

In [4]:
pip install pandas

Requirement already satisfied: pandas in /Users/raunakpurohit/first-flet-app/.venv/lib/python3.9/site-packages (2.3.3)
Requirement already satisfied: numpy>=1.22.4 in /Users/raunakpurohit/first-flet-app/.venv/lib/python3.9/site-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/raunakpurohit/first-flet-app/.venv/lib/python3.9/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/raunakpurohit/first-flet-app/.venv/lib/python3.9/site-packages (from pandas) (2026.3.post1)
Requirement already satisfied: tzdata>=2022.7 in /Users/raunakpurohit/first-flet-app/.venv/lib/python3.9/site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /Users/raunakpurohit/first-flet-app/.venv/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [13]:
import pandas as pd

prices = [500, 1000, 400, 700, 1100]
qty = [8, 11, 5, 2, 7]
names = ["A", "B", "C", "D", "E"]

s = pd.Series(prices, index=qty)
s

8      500
11    1000
5      400
2      700
7     1100
dtype: int64

In [40]:
data = {
    "pid" : [2,4,5,7,8],
    "names" : ["A", "B", "C", "D", "E"],
    "qty" : [8, 11, 5, 2, 7],
    "price" : [500, 1000, 400, 700, 1100],
}

df = pd.DataFrame(data, index=data["pid"])
df.head(2)

   pid names  qty  price
2    2     A    8    500
4    4     B   11   1000

In [42]:
df = pd.read_csv("student_scores.csv")
df

,Unnamed: 0,Gender,EthnicGroup,ParentEduc,LunchType,TestPrep,ParentMaritalStatus,PracticeSport,IsFirstChild,NrSiblings,TransportMeans,WklyStudyHours,MathScore,ReadingScore,WritingScore
0,0,female,NaN,bachelor's degree,standard,none,married,regularly,yes,3.0,school_bus,< 5,71,71,74
1,1,female,group C,some college,standard,NaN,married,sometimes,yes,0.0,NaN,05-Oct,69,90,88
2,2,female,group B,master's degree,standard,none,single,sometimes,yes,4.0,school_bus,< 5,87,93,91
3,3,male,group A,associate's degree,free/reduced,none,married,never,no,1.0,NaN,05-Oct,45,56,42
4,4,male,group C,some college,standard,none,married,sometimes,yes,0.0,school_bus,05-Oct,76,78,75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30636,816,female,group D,high school,standard,none,single,sometimes,no,2.0,school_bus,05-Oct,59,61,65
30637,890,male,group E,high school,standard,none,single,regularly,no,1.0,private,05-Oct,58,53,51
30638,911,female,NaN,high school,free/reduced,completed,married,sometimes,no,1.0,private,05-Oct,61,70,67
30639,934,female,group D,associate's degree,standard,completed,married,regularly,no,3.0,school_bus,05-Oct,82,90,93
30640,960,male,group B,some college,standard,none,married,never,no,1.0,school_bus,05-Oct,64,60,58

In [27]:
df.head()

,Unnamed: 0,Gender,EthnicGroup,ParentEduc,LunchType,TestPrep,ParentMaritalStatus,PracticeSport,IsFirstChild,NrSiblings,TransportMeans,WklyStudyHours,MathScore,ReadingScore,WritingScore
0,0,female,NaN,bachelor's degree,standard,none,married,regularly,yes,3.0,school_bus,< 5,71,71,74
1,1,female,group C,some college,standard,NaN,married,sometimes,yes,0.0,NaN,05-Oct,69,90,88
2,2,female,group B,master's degree,standard,none,single,sometimes,yes,4.0,school_bus,< 5,87,93,91
3,3,male,group A,associate's degree,free/reduced,none,married,never,no,1.0,NaN,05-Oct,45,56,42
4,4,male,group C,some college,standard,none,married,sometimes,yes,0.0,school_bus,05-Oct,76,78,75

In [29]:
df.tail()

,Unnamed: 0,Gender,EthnicGroup,ParentEduc,LunchType,TestPrep,ParentMaritalStatus,PracticeSport,IsFirstChild,NrSiblings,TransportMeans,WklyStudyHours,MathScore,ReadingScore,WritingScore
30636,816,female,group D,high school,standard,none,single,sometimes,no,2.0,school_bus,05-Oct,59,61,65
30637,890,male,group E,high school,standard,none,single,regularly,no,1.0,private,05-Oct,58,53,51
30638,911,female,NaN,high school,free/reduced,completed,married,sometimes,no,1.0,private,05-Oct,61,70,67
30639,934,female,group D,associate's degree,standard,completed,married,regularly,no,3.0,school_bus,05-Oct,82,90,93
30640,960,male,group B,some college,standard,none,married,never,no,1.0,school_bus,05-Oct,64,60,58

In [31]:
df.head(10)

,Unnamed: 0,Gender,EthnicGroup,ParentEduc,LunchType,TestPrep,ParentMaritalStatus,PracticeSport,IsFirstChild,NrSiblings,TransportMeans,WklyStudyHours,MathScore,ReadingScore,WritingScore
0,0,female,NaN,bachelor's degree,standard,none,married,regularly,yes,3.0,school_bus,< 5,71,71,74
1,1,female,group C,some college,standard,NaN,married,sometimes,yes,0.0,NaN,05-Oct,69,90,88
2,2,female,group B,master's degree,standard,none,single,sometimes,yes,4.0,school_bus,< 5,87,93,91
3,3,male,group A,associate's degree,free/reduced,none,married,never,no,1.0,NaN,05-Oct,45,56,42
4,4,male,group C,some college,standard,none,married,sometimes,yes,0.0,school_bus,05-Oct,76,78,75
5,5,female,group B,associate's degree,standard,none,married,regularly,yes,1.0,school_bus,05-Oct,73,84,79
6,6,female,group B,some college,standard,completed,widowed,never,no,1.0,private,05-Oct,85,93,89
7,7,male,group B,some college,free/reduced,none,married,sometimes,yes,1.0,private,> 10,41,43,39
8,8,male,group D,high school,free/reduced,completed,single,sometimes,no,3.0,private,> 10,65,64,68
9,9,female,group B,high school,free/reduced,none,married,regularly,yes,NaN,private,< 5,37,59,50

In [34]:
df.head(100)

,Unnamed: 0,Gender,EthnicGroup,ParentEduc,LunchType,TestPrep,ParentMaritalStatus,PracticeSport,IsFirstChild,NrSiblings,TransportMeans,WklyStudyHours,MathScore,ReadingScore,WritingScore
0,0,female,NaN,bachelor's degree,standard,none,married,regularly,yes,3.0,school_bus,< 5,71,71,74
1,1,female,group C,some college,standard,NaN,married,sometimes,yes,0.0,NaN,05-Oct,69,90,88
2,2,female,group B,master's degree,standard,none,single,sometimes,yes,4.0,school_bus,< 5,87,93,91
3,3,male,group A,associate's degree,free/reduced,none,married,never,no,1.0,NaN,05-Oct,45,56,42
4,4,male,group C,some college,standard,none,married,sometimes,yes,0.0,school_bus,05-Oct,76,78,75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,104,male,NaN,some college,standard,completed,married,regularly,yes,1.0,school_bus,> 10,100,88,94
96,105,female,group C,some college,standard,none,married,sometimes,yes,0.0,school_bus,05-Oct,58,67,72
97,106,female,group D,master's degree,standard,none,married,sometimes,no,3.0,private,05-Oct,87,100,100
98,107,male,group E,NaN,standard,completed,single,sometimes,yes,0.0,school_bus,05-Oct,66,63,64
99,108,female,group B,associate's degree,free/reduced,none,married,sometimes,yes,2.0,school_bus,05-Oct,52,76,70

In [43]:
df.sample(10)

,Unnamed: 0,Gender,EthnicGroup,ParentEduc,LunchType,TestPrep,ParentMaritalStatus,PracticeSport,IsFirstChild,NrSiblings,TransportMeans,WklyStudyHours,MathScore,ReadingScore,WritingScore
7951,415,female,group B,some high school,standard,none,married,regularly,yes,0.0,school_bus,NaN,65,74,75
958,10,male,group E,bachelor's degree,standard,none,NaN,regularly,yes,4.0,school_bus,< 5,99,99,100
20008,287,female,group D,some high school,standard,none,widowed,sometimes,yes,0.0,private,> 10,49,65,70
14375,250,male,group D,associate's degree,free/reduced,completed,married,sometimes,yes,3.0,private,05-Oct,54,54,47
30208,230,female,group A,high school,standard,none,married,regularly,no,3.0,school_bus,05-Oct,54,63,57
2062,171,male,group B,some college,free/reduced,none,single,sometimes,yes,2.0,private,NaN,54,53,48
26209,949,female,NaN,associate's degree,standard,none,married,regularly,yes,4.0,NaN,05-Oct,48,62,63
11769,478,female,group C,some college,standard,none,married,regularly,no,3.0,school_bus,05-Oct,50,58,55
7766,223,female,group C,some college,standard,none,single,never,no,1.0,school_bus,05-Oct,64,65,66
6076,410,male,group A,associate's degree,free/reduced,completed,married,never,NaN,5.0,school_bus,> 10,68,73,67

In [45]:
pip install openpyxl

Requirement already satisfied: openpyxl in /Users/raunakpurohit/first-flet-app/.venv/lib/python3.9/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /Users/raunakpurohit/first-flet-app/.venv/lib/python3.9/site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [48]:
# read the data from xlsx
df = pd.read_excel("ESD.xlsx")
df.head(10)

,EEID,Full Name,Job Title,Department,Business Unit,Gender,Ethnicity,Age,Hire Date,Annual Salary,Bonus %,Country,City,Exit Date
0,E02387,Emily Davis,Sr. Manger,IT,Research & Development,Female,Black,55,2016-04-08,141604,0.15,United States,Seattle,2021-10-16
1,E04105,Theodore Dinh,Technical Architect,IT,Manufacturing,Male,Asian,59,1997-11-29,99975,0.00,China,Chongqing,NaT
2,E02572,Luna Sanders,Director,Finance,Speciality Products,Female,Caucasian,50,2006-10-26,163099,0.20,United States,Chicago,NaT
3,E02832,Penelope Jordan,Computer Systems Manager,IT,Manufacturing,Female,Caucasian,26,2019-09-27,84913,0.07,United States,Chicago,NaT
4,E01639,Austin Vo,Sr. Analyst,Finance,Manufacturing,Male,Asian,55,1995-11-20,95409,0.00,United States,Phoenix,NaT
5,E00644,Joshua Gupta,Account Representative,Sales,Corporate,Male,Asian,57,2017-01-24,50994,0.00,China,Chongqing,NaT
6,E01550,Ruby Barnes,Manager,IT,Corporate,Female,Caucasian,27,2020-07-01,119746,0.10,United States,Phoenix,NaT
7,E04332,Luke Martin,Analyst,Finance,Manufacturing,Male,Black,25,2020-05-16,41336,0.00,United States,Miami,2021-05-20
8,E04533,Easton Bailey,Manager,Accounting,Manufacturing,Male,Caucasian,29,2019-01-25,113527,0.06,United States,Austin,NaT
9,E03838,Madeline Walker,Sr. Analyst,Finance,Speciality Products,Female,Caucasian,34,2018-06-13,77203,0.00,United States,Chicago,NaT

In [50]:
pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in /Users/raunakpurohit/first-flet-app/.venv/lib/python3.9/site-packages (9.4.0)
Note: you may need to restart the kernel to use updated packages.

In [58]:
# read the data from sql
import mysql.connector as conn

connection = conn.connect(
    host = "localhost",
    username = "root",
    password = "12345678",
    database = "classicmodels",
)

cur = connection.cursor()

cur.execute("""select * from customers where country = "USA";""")

data = cur.fetchall()

df = pd.DataFrame(data)
df

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,112,Signal Gift Stores,King,Jean,7025551838,8489 Strong St.,None,Las Vegas,NV,83030,USA,1166,71800.00
1,124,Mini Gifts Distributors Ltd.,Nelson,Susan,4155551450,5677 Strong St.,None,San Rafael,CA,97562,USA,1165,210500.00
2,129,Mini Wheels Co.,Murphy,Julie,6505555787,5557 North Pendale Street,None,San Francisco,CA,94217,USA,1165,64600.00
3,131,Land of Toys Inc.,Lee,Kwai,2125557818,897 Long Airport Avenue,None,NYC,NY,10022,USA,1323,114900.00
4,151,Muscle Machine Inc,Young,Jeff,2125557413,4092 Furth Circle,Suite 400,NYC,NY,10022,USA,1286,138500.00
5,157,Diecast Classics Inc.,Leong,Kelvin,2155551555,7586 Pompton St.,None,Allentown,PA,70267,USA,1216,100600.00
6,161,Technics Stores Inc.,Hashimoto,Juri,6505556809,9408 Furth Circle,None,Burlingame,CA,94217,USA,1165,84600.00
7,168,American Souvenirs Inc,Franco,Keith,2035557845,149 Spinnaker Dr.,Suite 101,New Haven,CT,97823,USA,1286,0.00
8,173,Cambridge Collectables Co.,Tseng,Jerry,6175555555,4658 Baden Av.,None,Cambridge,MA,51247,USA,1188,43400.00
9,175,Gift Depot Inc.,King,Julie,2035552570,25593 South Bay Ln.,None,Bridgewater,CT,97562,USA,1323,84300.00
10,181,Vitachrome Inc.,Frick,Michael,2125551500,2678 Kingston Rd.,Suite 101,NYC,NY,10022,USA,1286,76400.00
11,198,Auto-Moto Classics Inc.,Taylor,Leslie,6175558428,16780 Pompton St.,None,Brickhaven,MA,58339,USA,1216,23000.00
12,204,Online Mini Collectables,Barajas,Miguel,6175557555,7635 Spinnaker Dr.,None,Brickhaven,MA,58339,USA,1188,68700.00
13,205,Toys4GrownUps.com,Young,Julie,6265557265,78934 Hillside Dr.,None,Pasadena,CA,90003,USA,1166,90700.00
14,219,Boards & Toys Co.,Young,Mary,3105552373,4097 Douglas Av.,None,Glendale,CA,92561,USA,1166,11000.00
15,239,Collectable Mini Designs Co.,Thompson,Valarie,7605558146,361 Furth Circle,None,San Diego,CA,91217,USA,1166,105000.00
16,286,Marta's Replicas Co.,Hernandez,Marta,6175558555,39323 Spinnaker Dr.,None,Cambridge,MA,51247,USA,1216,123700.00
17,319,Mini Classics,Frick,Steve,9145554562,3758 North Pendale Street,None,White Plains,NY,24067,USA,1323,102700.00
18,320,Mini Creations Ltd.,Huang,Wing,5085559555,4575 Hillside Dr.,None,New Bedford,MA,50553,USA,1188,94500.00
19,321,Corporate Gift Ideas Co.,Brown,Julie,6505551386,7734 Strong St.,None,San Francisco,CA,94217,USA,1165,105000.00
20,328,Tekni Collectables Inc.,Brown,William,2015559350,7476 Moss Rd.,None,Newark,NJ,94019,USA,1323,43000.00
21,339,"Classic Gift Ideas, Inc",Cervantes,Francisca,2155554695,782 First Street,None,Philadelphia,PA,71270,USA,1188,81100.00
22,347,"Men 'R' US Retailers, Ltd.",Chandler,Brian,2155554369,6047 Douglas Av.,None,Los Angeles,CA,91003,USA,1166,57700.00
23,362,Gifts4AllAges.com,Yoshido,Juri,6175559555,8616 Spinnaker Dr.,None,Boston,MA,51003,USA,1216,41900.00
24,363,Online Diecast Creations Co.,Young,Dorothy,6035558647,2304 Long Airport Avenue,None,Nashua,NH,62005,USA,1216,114200.00
25,379,Collectables For Less Inc.,Nelson,Allen,6175558555,7825 Douglas Av.,None,Brickhaven,MA,58339,USA,1188,70700.00
26,424,Classic Legends Inc.,Hernandez,Maria,2125558493,5905 Pompton St.,Suite 750,NYC,NY,10022,USA,1286,67500.00
27,447,Gift Ideas Corp.,Lewis,Dan,2035554407,2440 Pompton St.,None,Glendale,CT,97561,USA,1323,49700.00
28,450,The Sharp Gifts Warehouse,Frick,Sue,4085553659,3086 Ingle Ln.,None,San Jose,CA,94217,USA,1165,77600.00
29,455,Super Scale Inc.,Murphy,Leslie,2035559545,567 North Pendale Street,None,New Haven,CT,97823,USA,1286,95400.00
30,456,Microscale Inc.,Choi,Yu,2125551957,5290 North Pendale Street,Suite 200,NYC,NY,10022,USA,1286,39800.00
31,462,FunGiftIdeas.com,Benitez,Violeta,5085552555,1785 First Street,None,New Bedford,MA,50553,USA,1216,85800.00
32,475,West Coast Collectables Co.,Thompson,Steve,3105553722,3675 Furth Circle,None,Burbank,CA,94019,USA,1166,55400.00
33,486,Motor Mint Distributors Inc.,Salazar,Rosa,2155559857,11328 Douglas Av.,None,Philadelphia,PA,71270,USA,1323,72600.00
34,487,Signal Collectibles Ltd.,Taylor,Sue,4155554312,2793 Furth Circle,None,Brisbane,CA,94217,USA,1165,60300.00
35,495,Diecast Collectables,Franco,Valarie,6175552555,6251 Ingle Ln.,None,Boston,MA,51003,USA,1188,85100.00

In [60]:
pip install requests

Requirement already satisfied: requests in /Users/raunakpurohit/first-flet-app/.venv/lib/python3.9/site-packages (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/raunakpurohit/first-flet-app/.venv/lib/python3.9/site-packages (from requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /Users/raunakpurohit/first-flet-app/.venv/lib/python3.9/site-packages (from requests) (3.8)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/raunakpurohit/first-flet-app/.venv/lib/python3.9/site-packages (from requests) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /Users/raunakpurohit/first-flet-app/.venv/lib/python3.9/site-packages (from requests) (2026.7.22)
Note: you may need to restart the kernel to use updated packages.

In [63]:
# fetching data from api
import requests as req

url = "https://jsonplaceholder.typicode.com/users"
try:
    request = req.get(url)
    
    request.raise_for_status()
    
    if request.status_code == 200:
        data = request.json()
        df = pd.DataFrame(data)
        df
    else:
        print("Something went wrong")
except:
    print("Something went wrong")
df

,id,name,username,email,address,phone,website,company
0,1,Leanne Graham,Bret,Sincere@april.biz,"{'street': 'Kulas Light', 'suite': 'Apt. 556',...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"{'street': 'Victor Plains', 'suite': 'Suite 87...",010-692-6593 x09125,anastasia.net,"{'name': 'Deckow-Crist', 'catchPhrase': 'Proac..."
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,"{'street': 'Douglas Extension', 'suite': 'Suit...",1-463-123-4447,ramiro.info,"{'name': 'Romaguera-Jacobson', 'catchPhrase': ..."
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,"{'street': 'Hoeger Mall', 'suite': 'Apt. 692',...",493-170-9623 x156,kale.biz,"{'name': 'Robel-Corkery', 'catchPhrase': 'Mult..."
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,"{'street': 'Skiles Walks', 'suite': 'Suite 351...",(254)954-1289,demarco.info,"{'name': 'Keebler LLC', 'catchPhrase': 'User-c..."
5,6,Mrs. Dennis Schulist,Leopoldo_Corkery,Karley_Dach@jasper.info,"{'street': 'Norberto Crossing', 'suite': 'Apt....",1-477-935-8478 x6430,ola.org,"{'name': 'Considine-Lockman', 'catchPhrase': '..."
6,7,Kurtis Weissnat,Elwyn.Skiles,Telly.Hoeger@billy.biz,"{'street': 'Rex Trail', 'suite': 'Suite 280', ...",210.067.6132,elvis.io,"{'name': 'Johns Group', 'catchPhrase': 'Config..."
7,8,Nicholas Runolfsdottir V,Maxime_Nienow,Sherwood@rosamond.me,"{'street': 'Ellsworth Summit', 'suite': 'Suite...",586.493.6943 x140,jacynthe.com,"{'name': 'Abernathy Group', 'catchPhrase': 'Im..."
8,9,Glenna Reichert,Delphine,Chaim_McDermott@dana.io,"{'street': 'Dayna Park', 'suite': 'Suite 449',...",(775)976-6794 x41206,conrad.com,"{'name': 'Yost and Sons', 'catchPhrase': 'Swit..."
9,10,Clementina DuBuque,Moriah.Stanton,Rey.Padberg@karina.biz,"{'street': 'Kattie Turnpike', 'suite': 'Suite ...",024-648-3804,ambrose.net,"{'name': 'Hoeger LLC', 'catchPhrase': 'Central..."